<?php

/**
 * -----------------------------------------------------------------------------
 * MessagingController (default module controller)
 * -----------------------------------------------------------------------------
 *
 * Scaffold controller generated by nwidart/laravel-modules. Real messaging
 * flows live inside Livewire components (agent-dashboard, conversation-thread,
 * message-composer, etc.), while webhooks and uploads are handled by their
 * dedicated controllers:
 *
 *   - WebChatController                             (public web-chat widget)
 *   - FileUploadController                          (attachment uploads)
 *   - Webhooks\TelegramWebhookController            (Telegram events)
 *   - Webhooks\WhatsAppWebhookController            (WhatsApp events)
 *
 * This class stays intentionally thin as per the project's controller rules.
 * -----------------------------------------------------------------------------
 */

namespace Modules\Messaging\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MessagingController extends Controller
{
    /** Render the module's landing page. */
    public function index()
    {
        return view('messaging::index');
    }

    /** Placeholder for the create form (not used — Livewire handles this). */
    public function create()
    {
        return view('messaging::create');
    }

    /** Placeholder store — real persistence flows through services. */
    public function store(Request $request)
    {
        // Intentionally left blank.
    }

    /** Placeholder show view. */
    public function show($id)
    {
        return view('messaging::show');
    }

    /** Placeholder edit view. */
    public function edit($id)
    {
        return view('messaging::edit');
    }

    /** Placeholder update endpoint. */
    public function update(Request $request, $id)
    {
        // Intentionally left blank.
    }

    /** Placeholder destroy endpoint. */
    public function destroy($id)
    {
        // Intentionally left blank.
    }
}
