<?php

// Variables
return [
    'creatorName' => 'Base Project',
    'creatorUrl' => 'https://tagiy.com',
    'templateName' => 'Base Project',
    'templateSuffix' => 'Base Project',
    'templateVersion' => '1.0.0',
    'templateFree' => false,
    'templateDescription' => 'Unlimited technology in communication',
    'templateKeyword' => 'NFC, NFC Cards, Tagiy NFC,',
    'licenseUrl' => 'https://themeforest.net/licenses/standard',
    'livePreview' => 'https://demos.pixinvent.com/vuexy-html-admin-template/landing/',
    'productPage' => 'https://1.envato.market/vuexy_admin',
    'support' => 'https://pixinvent.ticksy.com/',
    'moreThemes' => 'https://1.envato.market/pixinvent_portfolio',
    'documentation' => 'https://demos.pixinvent.com/vuexy-html-admin-template/documentation',
    'generator' => '',
    'changelog' => 'https://demos.pixinvent.com/vuexy/changelog.html',
    'repository' => 'https://github.com/pixinvent/vuexy-html-admin-template',
    'gitRepo' => 'pixinvent',
    'gitRepoAccess' => 'vuexy-html-admin-template',
    'githubFreeUrl' => 'https://tools.pixinvent.com/github/github-access',
    'facebookUrl' => 'https://www.facebook.com/pixinvents/',
    'twitterUrl' => 'https://twitter.com/pixinvents',
    'githubUrl' => 'https://github.com/pixinvent',
    'dribbbleUrl' => 'https://dribbble.com/pixinvent',
    'instagramUrl' => 'https://www.instagram.com/pixinvents/',
];
