<?php

/**
 * -----------------------------------------------------------------------------
 * BookingController (default module controller)
 * -----------------------------------------------------------------------------
 *
 * Scaffold controller generated by the module creator. It is kept as a simple
 * entry-point that renders the module landing view; the real booking flows
 * live in the role-specific controllers:
 *
 *   - Modules\Booking\Http\Controllers\Doctor\BookingController   (clinic UI)
 *   - Modules\Booking\Http\Controllers\Patient\BookingController  (patient UI)
 *   - Modules\Booking\Http\Controllers\Api\CalendarController     (JSON feeds)
 *
 * This class intentionally stays thin and free of business logic — see the
 * module CLAUDE.md for the "thin controllers" rule.
 * -----------------------------------------------------------------------------
 */

namespace Modules\Booking\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display the module's default landing page.
     * Used as a smoke-test route after installation.
     */
    public function index()
    {
        return view('booking::index');
    }

    /**
     * Show the create-booking form (stub).
     * Real booking creation is handled by the patient wizard Livewire flow.
     */
    public function create()
    {
        return view('booking::create');
    }

    /**
     * Persist a new booking (stub – kept for resource-route parity).
     * Real persistence goes through `Patient\BookingController` + actions.
     */
    public function store(Request $request)
    {
        // Intentionally empty – real store logic is implemented in the
        // role-specific controllers via FormRequest + Action classes.
    }

    /**
     * Display a single booking (stub).
     */
    public function show($id)
    {
        return view('booking::show');
    }

    /**
     * Show the edit form for a booking (stub).
     */
    public function edit($id)
    {
        return view('booking::edit');
    }

    /**
     * Update a booking (stub).
     */
    public function update(Request $request, $id)
    {
        // Kept intentionally empty – see role controllers.
    }

    /**
     * Delete a booking (stub).
     */
    public function destroy($id)
    {
        // Kept intentionally empty – cancellations use CancelBookingAction.
    }
}
